package com.springangularproject.springangularproject.application.application.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity // class will be mapped to a database table
@Table(name = "\"user\"") // Quote the table name to avoid SQL syntax error
public class User {

    @Id // marks it as the primary key
    @GeneratedValue(strategy = GenerationType.AUTO) // value of this field will be automatically generated by the database
    
    private long id;
    private final String name;
    private final String email;

    public User() { // no-argument constructor required by JPA to create instances of the User class
        this.name = "";
        this.email = "";
    }

    public User(String name, String email) { // constructor allows you to create a User object with specific values for
                                             // name and email.
        this.name = name;
        this.email = email;
    }

    /**
     * Returns the id of the user.
     * 
     * @return the id of the user
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the name of the user.
     * 
     * @return the name of the user
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the email of the user.
     * 
     * @return the email of the user
     */
    public String getEmail() {
        return email;
    }

    @Override
    public String toString() {
        return "User{" + "id=" + id + ", name=" + name + ", email=" + email + '}';
    }
}
